backend:
  name: git-gateway
  branch: main
media_folder: "public/assets/blog"
public_folder: "/assets/blog"
redirects:
  from = "/*"
  to = "https://www.seznam.cz/"
  status = 404
collections: 
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"], hint: "The post tag is the basic tag for displaying on the web. If you want to hide the post, delete this tag. Tag Use the 'featured' tag to display the post on the main page. Separate the tags with a comma 'post, featured, cars'." }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Image Alt", name: "imageAlt", widget: "string", hint: "Image description - for screen readers" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "page"
    label: "Page"
    folder: "src/page"
    create: true
    slug: "{{slug}}"
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "hidden", default: ["page"] }
      - { label: "Permalink", name: "permalink", widget: "hidden", default: "/{{ title | slugify }}/"}
  - name: "homepage"
    label: "Homepage"
    create: false 
    delete: false
    extension: json
    format: json
    editor: 
      preview: false
    files:
      - label: "Hero Section"
        name: "hero"
        file: "/src/_data/hero.json"
        fields:
            - name: title
              label: title
              widget: "string"
            - name: text
              label: text
              widget: "string"
            - name: image
              label: image
              widget: "image"
            - name: buttontext
              label: Button Text
              widget: "string"
            - name: buttonlink
              label: Button Link
              widget: "string"
      - label: "Our work section"
        name: "ourwork"
        file: "/src/_data/ourwork.json"
        fields:
            - label: "Our work description"
              name: "description"
              widget: "string"
            - label: "Carousel item"
              name: "carousel"
              widget: "list"
              fields: 
                - {label: Title, name: title, widget: string}
                - {label: Image, name: image, widget: image}
                - {label: Image Alt, name: imagealt, widget: string}
                - {label: Link, name: link, widget: string}
      - label: "Settings"
        name: "settings"
        file: "/src/_data/homepage.json"
        fields:
            - name: herovisible
              label: Is Hero section visible?
              widget: "boolean"
              default: true
            - name: articlesvisible
              label: Is Featured articles section visible?
              widget: "boolean"
              default: true
            - name: ourworkvisible
              label: Is Our work section visible?
              widget: "boolean"
              default: true
  - name: "settings"
    label: "Settings"
    create: false 
    delete: false
    extension: json
    format: json
    editor: 
      preview: false
    files:
      - label: "Meta Data"
        name: "meta"
        file: "/src/_data/site.json"
        fields:
          - name: name
            label: name
            widget: "string"
          - name: description
            label: description
            widget: "string"
          - name: favicon
            label: favicon
            widget: "image"
